client:
  market:
    server:
      port: 8080
client:
  market:
    spring:
      jpa:
      database: POSTGRESQL
        hibernate:
          ddl-auto: validate
        show-sql: true
      datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/gb_shop
        username: postgres
        password: password
        driverClassName: org.postgresql.Driver
      flyway:
        baseline-on-migrate: true
      
